# Generated by Django 3.0.5 on 2020-05-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
