# Generated by Django 3.0.5 on 2020-05-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadroom',
            name='image',
            field=models.ImageField(upload_to='img/residence'),
        ),
    ]
