# Generated by Django 3.0.5 on 2020-05-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0002_auto_20200504_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadroom',
            name='image',
            field=models.ImageField(null=True, upload_to='img/residence'),
        ),
    ]
