# Generated by Django 3.0.5 on 2020-05-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0005_auto_20200504_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadroom',
            name='image',
            field=models.FileField(upload_to='home/static/img/residence/'),
        ),
    ]
