# Generated by Django 3.0.5 on 2020-05-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhouse',
            name='image',
            field=models.ImageField(upload_to='home/static/img/house/'),
        ),
    ]
